# Generated by Django 4.0.4 on 2022-04-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
